### ISSUE TITLE
Fix Wall Walking

### ISSUE THREAD

**Issue by kaeberc** [julialwang/graphicsgame#15]
Currently, you are able to walk along the walls just by running against them. It also halts upwards momentum. Not sure _why_ this happens, but it's a problem. Especially when platforms you need to jump on are involved.

**Comment by kjy5** [comment]
This is happening because we are directly editing the lateral velocity of the player and the player is (probably) not falling down fast enough. This might be tied to #14. If the player falls correctly, then this behavior would less noticeable.
